<a href="https://colab.research.google.com/github/User28198/DS_tasks/blob/main/Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [2]:
np.__version__


'1.21.6'

In [3]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [4]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [5]:
a.itemsize

8

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [6]:
#method 1
np.add?

In [7]:
#method 2
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [8]:
a = np.zeros(10)
a[4] = 1
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [9]:
a = np.arange(10, 50)
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [10]:
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [11]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [12]:
a = np.array([1, 2, 0, 0, 4, 0])
b = np.nonzero(a)
b

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [13]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [14]:
#np.random.random((3,3,3))
np.random.randint(10, 20, 9)

array([17, 19, 14, 15, 10, 11, 11, 11, 14])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [15]:
a = np.random.random((10, 10, 10))
max = a.max()
min = a.min()
print(max, min)

0.9992972034411567 0.0008074599027844132


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [16]:
a = np.random.random(30)
a.mean()

0.43660699773397693

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [17]:
a = np.ones((7,7))
a[1:-1, 1:-1] = 0
a

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [18]:
a = np.ones((3,3))
np.pad(a, pad_width = 1, constant_values = 0)

array([[0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [19]:
a = np.diag(np.arange(1, 5),k=-1)
a


array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [20]:
a = np.ones((8,8))
a[1::2, ::2] = 0
a[::2, 1::2] = 0
a

array([[1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [21]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [22]:
a = np.array([[0,1], [1,0]])
np.tile(a, (4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [23]:
a = np.random.random((5,5))
a = (a-a.min()) / (a.max() - a.min())
a

array([[0.75165426, 0.10339582, 0.93408265, 0.45269244, 0.        ],
       [0.74775553, 0.86624994, 0.10453737, 0.59707602, 0.6646388 ],
       [0.54747415, 0.12123503, 0.9588758 , 0.36785658, 1.        ],
       [0.11488555, 0.11223505, 0.6490787 , 0.81153448, 0.38180017],
       [0.42687338, 0.18202309, 0.1898676 , 0.02450918, 0.80589115]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [24]:
a = np.dtype([('R', np.ubyte),
              ('G', np.ubyte),
              ('B', np.ubyte), 
              ('A', np.ubyte)])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [25]:
a = np.arange(15).reshape(5,3)
b = np.arange(6).reshape(3,2)
c = a @ b
c

array([[ 10,  13],
       [ 28,  40],
       [ 46,  67],
       [ 64,  94],
       [ 82, 121]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [26]:
a = np.arange(10)
a[(a>=3) & (a<=8)] *= -1
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

9

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

Except 'Z < Z > Z', all other expressions are legal

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [27]:
a = np.array(0) / np.array(0)
b = np.array(0) // np.array(0)
c = np.array([np.nan]).astype(int).astype(float)
print(a,b,c)


nan 0 [-9.22337204e+18]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [28]:
a = np.random.uniform(-1, 10, 10)
b = np.copysign(np.round(a, decimals = 0), a)
b

array([ 4.,  2.,  9.,  1., -1.,  5.,  4.,  9.,  8.,  2.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [29]:
a = np.array([1, 2.54, 4, 5.76, 5.5])
b = np.array([1, 2, 3, 4, 5])
np.intersect1d(a,b, return_indices = True)


(array([1., 4.]), array([0, 2]), array([0, 3]))

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [30]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today = np.datetime64('today')
tomorrow = np.datetime64('today') + np.timedelta64(1)
print(yesterday, today, tomorrow)

2022-08-21 2022-08-22 2022-08-23


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [31]:
a = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(a)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [32]:
A = np.array([1, 2, 3, 4, 5], dtype = 'float64')
B = np.array([1, 1, 1, 1, 1], dtype = 'float64')
np.add(A,B,out=B)
np.divide(A,2.0,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)


array([ -1.,  -3.,  -6., -10., -15.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [33]:
a = np.random.uniform(0, 25, 15)
b = (a - (a % 1))
c = np.floor(a)
d = np.ceil(a)
e = a.astype(int)
f = np.trunc(a)
print(a, '\n',b,'\n', c,'\n', d,'\n', e,'\n', f)

[23.00649823 17.35862701  9.39057144  9.56661135 15.45268435 17.35003309
 18.25151429  3.59682492  6.89855757 15.80354172  8.77449294 12.67344485
  9.9108111   2.59669409  7.74333922] 
 [23. 17.  9.  9. 15. 17. 18.  3.  6. 15.  8. 12.  9.  2.  7.] 
 [23. 17.  9.  9. 15. 17. 18.  3.  6. 15.  8. 12.  9.  2.  7.] 
 [24. 18. 10. 10. 16. 18. 19.  4.  7. 16.  9. 13. 10.  3.  8.] 
 [23 17  9  9 15 17 18  3  6 15  8 12  9  2  7] 
 [23. 17.  9.  9. 15. 17. 18.  3.  6. 15.  8. 12.  9.  2.  7.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [34]:
a = np.arange(5)
np.resize(a, ((5, 5)))

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [35]:
def generator():
  for x in range(10):
    yield x*x

a = np.fromiter(generator(), dtype = 'int64')
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [36]:
a = np.linspace(0, 1, 12)[1:-1]
a

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [37]:
a = np.random.random(10)
np.sort(a)

array([0.15373983, 0.16933393, 0.23248991, 0.26779552, 0.58174021,
       0.77353771, 0.77627268, 0.81170115, 0.88539196, 0.92007212])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [38]:
a = np.arange(5)
b = np.add.reduce(a)
b

10

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [39]:
A = np.random.random(5)
B = np.random.random(5)
c = np.allclose(A, B)
d = np.array_equal(A, B)
print(c, d)

False False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [40]:
x = np.arange(5)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [41]:
a = np.random.random((10,2))
x,y = a[:,0], a[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.79078285 0.87288746 1.123807   0.88320477 1.26506461 0.94559923
 0.87249977 0.40569795 0.24315582 0.68921372]
[0.15261522 0.36950035 0.70559524 0.25791423 0.85113399 0.39208168
 1.1678314  1.11119172 0.02367763 0.49055032]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [42]:
a = np.random.random(10)
b = a.argmax()
a[b] = 0
a


array([0.50117668, 0.0802068 , 0.76265394, 0.71526592, 0.5212427 ,
       0.44737629, 0.        , 0.43345468, 0.63536047, 0.30469568])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [43]:
a = np.zeros((3,3), [('x',float),('y',float)])
a['x'], a['y'] = np.meshgrid(np.linspace(0,1,3),
                             np.linspace(0,1,3))
print(a)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [44]:
X = np.array([1, 2, 3, 4, 5])
Y = np.array([6, 7, 8, 9, 10])
C = 1 / (np.subtract.outer(X, Y))
C

array([[-0.2       , -0.16666667, -0.14285714, -0.125     , -0.11111111],
       [-0.25      , -0.2       , -0.16666667, -0.14285714, -0.125     ],
       [-0.33333333, -0.25      , -0.2       , -0.16666667, -0.14285714],
       [-0.5       , -0.33333333, -0.25      , -0.2       , -0.16666667],
       [-1.        , -0.5       , -0.33333333, -0.25      , -0.2       ]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [45]:
for dtype in [np.int8, np.int16, np.int32, np.int64]:
  print("Min and Max value of", dtype, "is", np.iinfo(dtype).min, np.iinfo(dtype).max)
for dtype in [np.float16, np.float32, np.float64]:
  print('Min and Max value of', dtype, "is", np.finfo(dtype).min, np.finfo(dtype).max)


Min and Max value of <class 'numpy.int8'> is -128 127
Min and Max value of <class 'numpy.int16'> is -32768 32767
Min and Max value of <class 'numpy.int32'> is -2147483648 2147483647
Min and Max value of <class 'numpy.int64'> is -9223372036854775808 9223372036854775807
Min and Max value of <class 'numpy.float16'> is -65500.0 65500.0
Min and Max value of <class 'numpy.float32'> is -3.4028235e+38 3.4028235e+38
Min and Max value of <class 'numpy.float64'> is -1.7976931348623157e+308 1.7976931348623157e+308


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [46]:
#np.set_printoptions(threshold = float('inf'))
a = np.arange(10000)
a

array([   0,    1,    2, ..., 9997, 9998, 9999])

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [47]:
a = np.random.uniform(1, 10, size = 10)
b = 7.6543
index = np.abs(a-b).argmin()
print('Closest value to', b, 'in', a, 'is', a[index])

Closest value to 7.6543 in [1.35056771 2.61271859 4.09757453 5.02598106 8.25858275 2.29630021
 1.89515995 8.5525494  7.61570492 9.72113538] is 7.615704923993519


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [48]:
a = np.zeros(10, [('position', [('x', float),
                               ('y', float)]),
                 ('color', [('r', float),
                            ('g', float),
                            ('b', float)])])
a

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [49]:
a = np.random.random((100,2))
x, y = np.atleast_2d(a[:,0],a[:,1])
distance = np.sqrt((x-x.T)**2 + (y-y.T)**2)
distance

array([[0.        , 0.6068777 , 0.70605606, ..., 0.52975785, 0.87493767,
        0.78449199],
       [0.6068777 , 0.        , 0.22390659, ..., 0.18691423, 0.77167352,
        0.24204805],
       [0.70605606, 0.22390659, 0.        , ..., 0.4070644 , 0.99494133,
        0.09374389],
       ...,
       [0.52975785, 0.18691423, 0.4070644 , ..., 0.        , 0.60015945,
        0.42812664],
       [0.87493767, 0.77167352, 0.99494133, ..., 0.60015945, 0.        ,
        0.99237705],
       [0.78449199, 0.24204805, 0.09374389, ..., 0.42812664, 0.99237705,
        0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [50]:
a = np.arange(10, dtype = 'float32')
b = a.astype('int32')
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [51]:
#StringIO - In memory file-like object
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11''')

a = np.genfromtxt(s, delimiter = ',')
a

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)